spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foodly?currentSchema=foodly
    username: foodly
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # could be also create-drop
    show-sql: true
        # format_sql: true